logging:
    level:
        cn.kxlove: TRACE
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://google.kxlove.cn/happy?useSSL=false
    username: root
    password: Aa63708923
  output:
    ansi:
      enabled: always


mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: cn.kxlove.flywaydb.domain
mapper:
  mappers:
    - cn.kxlove.flywaydb.MyMapper
  before: true
flyway:
  baseline-on-migrate: true